#!/bin/bash
#############################################################################
#
#Author : Sreejith
#Version: V1
#Usage : For loop to print incremental of 10 numbers
#
#############################################################################

#Dispay the date 
echo "Date: $(date +%F)"
echo "Time: $(date +%H:%M:%S)"

for i in {1..100}
do 
	echo $i
	$i=$(i+10) 
done

